name: verify
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: mathcomp/mathcomp:2.5.0-rocq-prover-9.1
          custom_script: |
            startGroup "Workaround permission issue"
              sudo chown -R coq:coq .
            endGroup
            startGroup "Install MathComp-Analysis 1.16, zify and Algebra-Tactics"
              opam update -y
              opam install -y -j 4 coq-mathcomp-analysis.1.16.0 coq-mathcomp-zify coq-mathcomp-algebra-tactics
            endGroup
            startGroup "Verify"
              bash ci/verify.sh
            endGroup
